kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: prometheus-node-exporter-1 
spec:
  selector:
      app: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100
  type: NodePort
